#!/usr/bin/env bash

# Deploy to github pages
STATUS="$(git status)"

if [[ $STATUS == *"nothing to commit"* ]]
then
    git config --global user.email "you@example.com"
    git config --global user.name "CircleCI"
    git rm .gitignore
    git add public
    git commit -m "Remove .gitignore and add public to publish"
    git subtree push --prefix public origin gh-pages
    ## does not work this
    # git push origin `git subtree split --prefix public master`:gh-pages --force
    git reset HEAD~
    git checkout .gitignore
else
    echo "Need clean working directory to publish"
fi
