#!/usr/bin/env bash

# Deploy to github pages
STATUS="$(git status)"

if [[ $STATUS == *"nothing to commit"* ]]
then
    sed -i "" '/public/d' ./.gitignore
    git add .
    git commit -m "Edit .gitignore to publish"
    git subtree push --prefix public origin gh-pages
    ## does not work this
    # git push origin `git subtree split --prefix public master`:gh-pages --force
    git reset HEAD~
    git checkout .gitignore
else
    echo "Need clean working directory to publish"
fi
